package com.xuwb.librarysystem.mappers;

import com.xuwb.librarysystem.models.BorrowInfo;
import com.xuwb.librarysystem.models.InfoEntity;

public interface BorrowInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbggenerated
     */
    int insert(BorrowInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbggenerated
     */
    int insertSelective(BorrowInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbggenerated
     */
    BorrowInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BorrowInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BorrowInfo record);

    int updateByInfoEntity(InfoEntity infoEntity);

    BorrowInfo selectByBacktime();
}