package com.xuwb.librarysystem.models;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.isbn
     *
     * @mbggenerated
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.pages
     *
     * @mbggenerated
     */
    private Integer pages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.is_lend
     *
     * @mbggenerated
     */
    private IsLend isLend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.max_backtime
     *
     * @mbggenerated
     */
    private Integer maxBacktime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.id
     *
     * @return the value of book_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.id
     *
     * @param id the value for book_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.name
     *
     * @return the value of book_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.name
     *
     * @param name the value for book_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.isbn
     *
     * @return the value of book_info.isbn
     *
     * @mbggenerated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.isbn
     *
     * @param isbn the value for book_info.isbn
     *
     * @mbggenerated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.pages
     *
     * @return the value of book_info.pages
     *
     * @mbggenerated
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.pages
     *
     * @param pages the value for book_info.pages
     *
     * @mbggenerated
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.is_lend
     *
     * @return the value of book_info.is_lend
     *
     * @mbggenerated
     */
    public IsLend getIsLend() {
        return isLend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.is_lend
     *
     * @param isLend the value for book_info.is_lend
     *
     * @mbggenerated
     */
    public void setIsLend(IsLend isLend) {
        this.isLend = isLend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.max_backtime
     *
     * @return the value of book_info.max_backtime
     *
     * @mbggenerated
     */
    public Integer getMaxBacktime() {
        return maxBacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.max_backtime
     *
     * @param maxBacktime the value for book_info.max_backtime
     *
     * @mbggenerated
     */
    public void setMaxBacktime(Integer maxBacktime) {
        this.maxBacktime = maxBacktime;
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", isbn='" + isbn + '\'' +
                ", pages=" + pages +
                ", isLend=" + isLend +
                ", maxBacktime=" + maxBacktime +
                '}';
    }
}